Order model
Alexsandr-Yablunovskyi/book-store pull request #10
Opened 2023-12-01 04:30 UTC by Alexsandr-Yablunovskyi

2023-12-01 15:57 UTC, OlehReex approved these changes
Looks like you should separate Order and ShoppingCart PR`s

2023-12-01 15:57 UTC, OlehReex commented on src/main/java/yablunovskyi/bookstore/service/impl/OrderServiceImpl.java
> +        order.setUser(user);
You can create mapper to implement this logic

2023-12-04 08:43 UTC, Elena-Bruyako requested changes
There are changes from Shopping Cart HW, please fix it

2023-12-11 07:00 UTC, Elena-Bruyako approved these changes
Good job!

2023-12-12 13:25 UTC, merged