Add dto concept
Alexsandr-Yablunovskyi/book-store pull request #2
Opened 2023-10-17 11:08 UTC by Alexsandr-Yablunovskyi

DTO and mapper packages are created. New methods (findById and findAllByAuthor) are implemented. EntityNotFoundException is created. All requared configuration are implemented

2023-10-17 12:06 UTC, validatorr approved these changes
Great job!

2023-10-17 12:06 UTC, validatorr commented on src/main/java/yablunovskyi/bookstore/BookStoreApplication.java
> +    }
I'm not sure that this block of code required here, we are not using it anywhere

2023-10-17 12:06 UTC, validatorr commented on src/main/java/yablunovskyi/bookstore/controller/BookController.java
> +    public List<BookDto> findAll() {
Correct me if I'm wrong, but we should use find when we want to return Optional(on repository layer) and get on other layers

2023-10-17 13:28 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/BookStoreApplication.java
> +    }
agree! Let’s  remove it;)

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/config/MapperConfig.java
> +public class MapperConfig {
it is better to specify @MapperConfig directly on mapper class

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/controller/BookController.java
> +    @GetMapping("/by-author")
you will realize `/search` in the next task ;)

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/controller/BookController.java
> +
```suggestion
```

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/dto/BookDto.java
> +public class BookDto {
it is better to use records for DTO (apply  to all dtos) 

upgrade your maven-checkstyle-plugin to 3.3.0 if Checkstyle fires at records

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/model/Book.java
> +@Data
Lombok is a great library but be [attentive when using it with Entity](https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/) JFYI

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/model/Book.java
> +    private String coverImage;
```suggestion
    private BigDecimal price;
    private String description;
    private String coverImage;
```

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/repository/impl/BookRepositoryImpl.java
> +        }
Let’s  add catch block

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/repository/impl/BookRepositoryImpl.java
> +
```suggestion
```

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/repository/impl/BookRepositoryImpl.java
> +    public List<Book> findAllByAuthor(String author) {
You can leave it for now but don’t forget remove it when you add `search `

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/service/impl/BookServiceImpl.java
> +        }*/
Let’s remove commented code ;)

2023-10-17 13:28 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
there is a map method, so that you can do everything in a single chain

2023-10-19 14:56 UTC, liliia-ponomarenko approved these changes
Great! But fix my comment before merging ;)

2023-10-19 14:56 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/controller/BookController.java
> +    */
Better don’t  leave commented code

2023-10-19 14:56 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/service/BookService.java
> +    /*List<BookDto> findAllByAuthor(String author);*/
the same

2023-10-19 14:56 UTC, liliia-ponomarenko commented on src/main/java/yablunovskyi/bookstore/service/impl/BookServiceImpl.java
> +    }*/
the same

2023-10-27 09:32 UTC, merged